# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0bdae53c1cbc0c132d57294f85793538fc55b76ea643f26b0c7561ce5d673697c105a1a2a102d1da909b31b1420900b00b31fb96b84c269b4328145f5e7858e9

test:
  secret_key_base: 9b84c36e2f27305133c03119d6e15b5d559c1e9181752abee3b2777610f1042365faad9e9d596802045b0383181180a3d180f14aef2223f6f86e0e2f7cc47fd9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
